import Head from 'next/head'
import { getSession, useSession } from 'next-auth/react'
import Login from '@/components/Login'
import Sidebar from '@/components/Sidebar'
import Feed from '@/components/Feed'
import Trending from '@/components/Trending'


export default function Home() {

  const { data: session } = useSession()


  if (!session) return <Login />



  return (
    <>
      <Head>
        <title>Twitter-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter.jpg" />
      </Head>
      <main>
        <Sidebar />
        <div className='flex gap-6'>
            <Feed />
            <Trending />
           
            
        </div>
        
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
